name: "GitHub Action Test"
on: 
  workflow_dispatch:

jobs:
  Display_github_value:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: "Output"
        run: |
          pwd
          echo ${{ github.actor }}
          echo ${{ github.actor_id }}
          echo ${{ github.event_name }}
          echo ${{ github.head_ref }}
          echo ${{ github.job }}
          echo ${{ github.path }}
          echo ${{ github.ref }}
          echo ${{ github.ref_name }}
          echo ${{ github.ref_type }}
          echo ${{ github.event.inputs.branch_name }}
          echo ${{ secrets.SECRET_NAME }}
          echo ${{ secrets.PH_PAT }}
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_NAME }}
